<?php
/**
 * Created by PhpStorm.
 * User: Jiefu Yang
 * Date: 19/12/2015/019
 * Time: 1:02 PM
 */

class ManageModel extends Model{
    public function __construct()
    {
        $this->_fields = array('id','user','pass','level','login_count','last_ip','last_time','reg_time');
        $this->_tables = array(DB_PREFIX.'manage');
        parent::__construct();
    }

    public function findAll()
    {
        return parent::select(array('id','user','level','login_count','last_ip','last_time'),
                              array('limit'=>$this->_limit,'order'=>'id ASC'));
    }

    public function findOne()
    {
        $_oneData = $this->_request->one($this->_fields);
        return parent::select(array('id','user','level'),
                              array('where'=>$_oneData,'limit'=>'1'));
    }

    public function total()
    {
        return parent::total(); // TODO: Change the autogenerated stub
    }

    public function add()
    {
        $_addData = $this->_request->add($this->_fields);
        $_addData['pass'] = sha1($_addData['pass']);
        $_addData['last_ip'] = Tool::getIP();
        $_addData['reg_time'] = Tool::getDate();

        return parent::add($_addData);
    }

    public function update()
    {
        $_oneData = $this->_request->one($this->_fields);
        $_updateData = $this->_request->update($this->_fields);
        $_updateData['pass'] = sha1($_updateData['pass']);

        return parent::update($_oneData,$_updateData);
    }

    public function delete()
    {
        $_deleteData = $this->_request->delete($this->_fields);
        return parent::delete($_deleteData);
    }

    //判断输入是否为一
    public function isOne($_OneData)
    {
        return parent::isOne($_OneData);
    }

    public function isUser()
    {
        $this->_check->ajax($this);
    }
}