<?php
/**
 * Created by PhpStorm.
 * User: Jiefu Yang
 * Date: 19/12/2015/019
 * Time: 1:02 PM
 */

class ManageModel extends Model{
    public function __construct()
    {
        parent::__construct();
        $this->_fields = array('id','user','pass','level','login_count','last_ip','last_time','reg_time');
        $this->_tables = array(DB_PREFIX.'manage');
    }

    public function findAll()
    {
        $this->_tables = array(DB_PREFIX.'manage a',DB_PREFIX.'level b');
        return parent::select(array('a.id','a.user','a.level','a.login_count','a.last_ip','a.last_time','b.level_name'),
                              array('limit'=>$this->_limit,'order'=>'id ASC','where'=>'a.level=b.id'));
    }

    public function findOne()
    {
        $_oneData = $this->getRequest()->one($this->_fields);
        return parent::select(array('id','user','level'),
                              array('where'=>$_oneData,'limit'=>'1'));
    }

    public function total()
    {
        return parent::total(); // TODO: Change the autogenerated stub
    }

    public function add()
    {
        $_addData = $this->getRequest()->add($this->_fields);
        $_addData['pass'] = sha1($_addData['pass']);
        $_addData['last_ip'] = Tool::getIP();
        $_addData['reg_time'] = Tool::getDate();

        return parent::add($_addData);
    }

    public function update()
    {
        $_oneData = $this->getRequest()->one($this->_fields);
        $_updateData = $this->getRequest()->update($this->_fields);
        $_updateData['pass'] = sha1($_updateData['pass']);

        return parent::update($_oneData,$_updateData);
    }

    public function isUser()
    {
        $this->_check->ajax($this);
    }
}